#Laboratorio de predicción lineal

22.46 Procesamiento adaptativo de señales aleatorias

© 2019 Ariel Nowik, Rocío Parra

In [0]:
# Antes de comenzar, importamos las librerias que utilizaremos
# a lo largo del informe

from IPython.display import clear_output
from scipy.io.wavfile import read
import numpy as np
import IPython.display as ipd
import matplotlib.pyplot as plt
import wave
import math
from IPython.display import Audio
from scipy import signal as sgn
import scipy

In [0]:
# Descargamos los archivos que procesaremos 
! wget "https://drive.google.com/open?id=1GJacuJ7R8kOW1UXvGAOXSaHrY0bbkhN9" -o "aa.wav"
! wget "https://drive.google.com/open?id=1DAV5xu-VP9P73sAtsDO9i7MvuFjgT0OB" -o "sh.wav"

In [0]:
# Definiciones de funciones genericas

def get_signal(wav_path):
    _, data = read(wav_path)
    print(data)
    signal = np.array(data,dtype=float) 
    norm = np.linalg.norm(signal)
    print(signal)
    print(norm)
    return signal/np.linalg.norm(signal)  # return normalized version

In [17]:
# Configuraciones generales
fs = 8000.0
aa = get_signal("pasa-g3-8k-aa.wav")
sh = get_signal("pasa-g3-8k-sh.wav")

[ 0  0  0 ...  7  2 -2]
[ 0.  0.  0. ...  7.  2. -2.]
161078.64648053137
[ 0  0  0 ... -2  6 -3]
[ 0.  0.  0. ... -2.  6. -3.]
123695.51149496088


In [18]:
# Escuchamos los audios originales
# Sonido /a/
Audio(aa,rate=fs)

In [19]:
# Sonido /sh/
Audio(sh, rate=fs)